[CRAWLER]
# 数据爬取配置
# 用户代理
USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
TIME_OUT = 10
MAX_RETRIES = 3
# 登录地址
BILIBILI_LOGIN_URL = https://www.bilibili.com
# 音频榜单API
AUDIO_RANK_ALL_PERIOD_URL = https://api.bilibili.com/x/copyright-music-publicity/toplist/all_period
AUDIO_RANK_DETAIL_URL = https://api.bilibili.com/x/copyright-music-publicity/toplist/detail
AUDIO_RANK_MUSIC_LIST_URL = https://api.bilibili.com/x/copyright-music-publicity/toplist/music_list

[LOGGING]
# 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
LEVEL = INFO
# 日志格式
LOG_FORMAT = %%(asctime)s - %%(name)s - %%(levelname)s - %%(message)s
DATE_FORMAT = %%Y-%%m-%%d %%H:%%M:%%S
# 日志文件路径
PATH = logs/