[DEFAULT]
# 默认配置

[CRAWLER]
# B站登录URL
login_url = https://www.bilibili.com/
# 音频榜单API
audio_rank_all_period_url = https://api.bilibili.com/x/copyright-music-publicity/toplist/all_period
audio_rank_detail_url = https://api.bilibili.com/x/copyright-music-publicity/toplist/detail
audio_rank_music_list_url = https://api.bilibili.com/x/copyright-music-publicity/toplist/music_list
# 请求头
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.59
# 请求超时时间(秒)
timeout = 10
# 请求间隔时间(秒)
interval = 3
# Cookie保存路径
cookie_path = data/raw/cookies.json

[DATA]
# 原始数据保存路径
raw_data_path = data/raw
# 处理后数据保存路径
processed_data_path = data/processed
# 停用词文件路径
stopwords_path = data/stopwords.txt

[LOGGING]
# 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = INFO
# 日志格式
format = %%(asctime)s - %%(name)s - %%(levelname)s - %%(message)s
# 日志文件路径
file_path = logs/bilibili_crawler.log